FROM eclipse-temurin:21-jdk

WORKDIR /app

COPY mvnw pom.xml ./
COPY .mvn .mvn

RUN chmod +x mvnw

COPY src src

EXPOSE 8080
EXPOSE 5005

CMD ["./mvnw", "-Dspring-boot.run.fork=false", "spring-boot:run"]