spring.application.name=backend
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/booklibrary_dev}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:booklibrary}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:booklibrary}
spring.jpa.hibernate.ddl-auto=update
spring.devtools.restart.enabled=true
spring.devtools.restart.poll-interval=2s
spring.devtools.restart.quiet-period=1s
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always